### PR TITLE
Created a hashtag trollbox

### PR DESCRIPTION
**Pull request by joshuam10o**
only a suggestion: at the request of several people from support channel on slack.

### CODE REVIEW

**Comment by kingflurkel** [comment]
Gonna check it in the morning!

**Comment by faffydee** [comment]
I don't see the added value of putting this functionality in our app. It could be a great seperate app/website though! It just doesn't belong in the app imo: there we should focus on the main functionalities to keep it clear and easy to use/overview.

**Comment by joshuam10o** [comment]
I counter that it only has use because it's in the app: people are misunderstanding the hashtaglist as a forum-like interface and expecting to be able to reply to responses. It'll be more useful to be able to have some degree of "out of channel" communication within the app, especially because we apparently can only access deal chat after both parties have given their deposits: way too late IMO.

**Comment by faffydee** [comment]
I'd think giving the functionality of just chatting about the hashtag, right next to the actual functionality of posting a request is confusing. It will only create more confusion as to where you got to do what. I think a link in the hashtag-info-box (something like "Talk about this hashtag") that links to an external website/app/chatterbox (or even a slack channel with that #-name) will be a better solution.

Only chatting when you're both invested in a deal is spam-prevention.

**Comment by BvL13** [comment]
Sorry for getting involved. I think the problem is not described well and therefore the solution might not fit. 
Joshua can you simply define the issue first. What is the behavior now, what is the expected behavior. Then the solution should be simple.

**Comment by sponnet** [comment]
I can see the benefit of some out of band communication, but I want to avoid putting extra features in the app before they fit in a larger vision and before the MVP is well tested and bugs have been ironed out.

**Comment by kingflurkel** [comment]
Agree with @sponnet.

**Pull request closed without merging**
